#!/usr/bin/env bash
# Hot-reload an extension in the LIVE session — no logout after the first run.
#
# GNOME caches JS modules per URL and won't discover new extension dirs without
# a restart, so we install the extension under its real uuid with a tiny loader
# extension.js that dynamically imports the real code from impl/ with a
# cache-busting ?v=N. Every relative import in impl/ is rewritten to carry the
# same N, so each run loads fresh code after `gnome-extensions disable/enable`.
#
# Usage: scripts/dev.sh sticky-notes     (first run on a new uuid needs ONE relogin)
set -euo pipefail
name="$1"
src="$(cd "$(dirname "$0")/.." && pwd)/extensions/$name"
uuid=$(python3 -c "import json;print(json.load(open('$src/metadata.json'))['uuid'])")
dest="$HOME/.local/share/gnome-shell/extensions/$uuid"
v=$(date +%s)

# remove leftovers from the old rotating-uuid approach
rm -rf "$HOME"/.local/share/gnome-shell/extensions/"${uuid%@*}"-dev*@"${uuid#*@}" 2>/dev/null || true

mkdir -p "$dest/impl"
# top-level files the shell itself reads
cp "$src/metadata.json" "$dest/metadata.json"
[ -f "$src/stylesheet.css" ] && cp "$src/stylesheet.css" "$dest/stylesheet.css"
if [ -d "$src/schemas" ]; then rm -rf "$dest/schemas"; cp -r "$src/schemas" "$dest/schemas"; glib-compile-schemas "$dest/schemas" 2>/dev/null || true; fi
# real code under impl/ with versioned relative imports
rm -f "$dest"/impl/*.js
for f in "$src"/*.js; do
  sed -E "s#(from ['\"]\./[A-Za-z0-9_./-]+\.js)(['\"])#\1?v=$v\2#g" "$f" > "$dest/impl/$(basename "$f")"
done
echo "$v" > "$dest/impl/VERSION"
cat > "$dest/extension.js" <<'J'
// Generated by scripts/dev.sh — hot-reload loader. Real code lives in impl/.
import {Extension} from 'resource:///org/gnome/shell/extensions/extension.js';
import Gio from 'gi://Gio';

export default class DevLoader extends Extension {
    enable() {
        this._cancelled = false;
        const [, bytes] = Gio.File.new_for_path(`${this.path}/impl/VERSION`).load_contents(null);
        const v = new TextDecoder().decode(bytes).trim();
        import(`file://${this.path}/impl/extension.js?v=${v}`).then(m => {
            if (this._cancelled) return;
            this._impl = new m.default(this.metadata);
            this._impl.enable();
        }).catch(e => console.error(`[dev-loader] ${e}\n${e.stack}`));
    }
    disable() {
        this._cancelled = true;
        this._impl?.disable();
        this._impl = null;
    }
}
J

if ! gnome-extensions info "$uuid" >/dev/null 2>&1; then
  echo "NEW uuid: $uuid is installed but the shell can't see it yet -> log out/in ONCE, then run this script after each edit."
  exit 0
fi
gnome-extensions disable "$uuid" 2>/dev/null || true
sleep 0.3
gnome-extensions enable "$uuid"
gnome-extensions info "$uuid" | grep -E "State|Enabled"
echo "reloaded v=$v   logs: journalctl -f _COMM=gnome-shell | grep -i -E 'sticky|dev-loader|JS ERROR'"
